version: '{build}'

branches:
  only:
    - master

# TODO: add "Visual Studio 2017" image

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    COMPILER: msvc2015
    BUILDTOOL: meson
    CONFIGURATION: Debug
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    TARGET: build
    PLATFORM: x64

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    COMPILER: msys2
    BUILDTOOL: meson
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    TARGET: build
    PLATFORM: x64

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    COMPILER: msys2
    BUILDTOOL: cmake
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    TARGET: importer
    PLATFORM: x64

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    COMPILER: msvc2015
    BUILDTOOL: cmake
    CONFIGURATION: Debug
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    TARGET: build
    PLATFORM: x64

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    COMPILER: msys2
    BUILDTOOL: cmake
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    TARGET: build
    PLATFORM: x64

  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
    BUILDTOOL: cmake
    CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Debug -DOSMSCOUT_BUILD_BINDING_JAVA=OFF
    COMPILER: gcc

  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
    BUILDTOOL: cmake
    CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Debug -DOSMSCOUT_BUILD_BINDING_JAVA=OFF
    COMPILER: clang

    # make sure that library can be built with all debugging code
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
    BUILDTOOL: cmake
    CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Debug -DOSMSCOUT_BUILD_BINDING_JAVA=OFF -DLABEL_LAYOUTER_DEBUG=ON -DDEBUG_GROUNDTILES=ON -DDEBUG_COASTLINE=ON -DDEBUG_TILING=ON -DDEBUG_ROUTING=ON
    COMPILER: gcc

  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
    BUILDTOOL: meson
    COMPILER: gcc

  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
    BUILDTOOL: meson
    COMPILER: clang

install:
- cmd: set
- cmd: '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\install.bat'
- sh: env
- sh: 'sudo --preserve-env ${APPVEYOR_BUILD_FOLDER}/ci/appveyor/install.sh'

build_script:
# cmd is executed on windows only, sh is executed just on Ubuntu
- cmd: '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\build.bat'
- sh: '${APPVEYOR_BUILD_FOLDER}/ci/appveyor/build.sh'

test_script:
- sh: '${APPVEYOR_BUILD_FOLDER}/ci/appveyor/test.sh'

deploy:
  provider: GitHub
  description: ''
  auth_token:
    secure: Aj9mbq43PDgYOWS4LsWkDC3UQIgPGlL8NGdUKRTRA7GZhirzOhzDyXqM7SUIk8iU
  artifact: libosmscout-importer-Windows-x86_64.zip
  on:
    branch: master
    appveyor_repo_tag: true
    target: importer

notifications:
- provider: Email
  to:
  - tim@framstag.com
  on_build_failure: true
  on_build_status_changed: true

for:
-
  matrix:
    only:
    - image: Visual Studio 2015
  cache:
  - c:\tools\vcpkg\installed\